name: Bug Report
description: Found something unexpected in ProcessGit? Report it here.
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve ProcessGit. Please include as much context as possible so we can reproduce the issue quickly.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: ProcessGit version / commit
      description: Include the binary tag or commit SHA you are running.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Reproduction steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: dropdown
    id: artifacts
    attributes:
      label: BPMN/UAPF file attached?
      options:
        - "Yes (attached or linked)"
        - "No (not available)"
    validations:
      required: true
  - type: textarea
    id: viewer-diff-validator
    attributes:
      label: Viewer / diff / validator steps
      description: |
        Describe any viewer, diagram diff, or validator actions that show the problem (e.g., open BPMN viewer on file X, run UAPF validation rule Y).
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste or link logs with secrets removed.
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      options:
        - label: Docker / containerized
        - label: Package or binary install
        - label: Source build
        - label: Other (describe below)
  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Databases, OS/arch, proxies, or anything else that could help us diagnose the issue.
