name: Feature Request
description: Suggest a new ProcessGit capability.
labels: ["type/proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Tell us what process-first capability you want in ProcessGit.
  - type: textarea
    id: summary
    attributes:
      label: Feature summary
      placeholder: |
        I would like ProcessGit to...
    validations:
      required: true
  - type: textarea
    id: artifacts
    attributes:
      label: Process artifacts (BPMN/DMN/CMMN/UAPF)
      description: Which artifact types or formats should this feature focus on?
  - type: textarea
    id: expected-ux
    attributes:
      label: Expected UX (repo file view / PR diff / release)
      description: Describe where this should appear in the UI (file viewer, PR diff, release page, etc.) and what the user should see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / problem statement
      description: What user problem does this solve?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any workarounds or other tools you’ve tried.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Related links, diagrams, or references.
