#!/bin/bash
[[ -f ./setup ]] && source ./setup

pushd /app/gitea >/dev/null
su-exec $USER /app/processgit-seed --config /data/gitea/conf/app.ini || exit 1
exec su-exec $USER /app/gitea/gitea web --config /data/gitea/conf/app.ini
popd
